const cfg=window.VIRALIZA_CONFIG||{};
const configured=cfg.SUPABASE_URL && !cfg.SUPABASE_URL.includes("COLE_") && cfg.SUPABASE_ANON_KEY && !cfg.SUPABASE_ANON_KEY.includes("COLE_");
const sb=configured?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const demoTrends=[
{id:1,name:"Áudio Nostalgia",category:"Música",platform:"TikTok",growth:87,status:"Emergente",score:97,description:"Áudios nostálgicos estão ganhando força em vídeos de rotina, moda e storytelling."},
{id:2,name:"Quiet Luxury",category:"Moda",platform:"Instagram",growth:64,status:"Em alta",score:84,description:"Conteúdos minimalistas e sofisticados continuam crescendo entre marcas e criadores."},
{id:3,name:"Get Ready With Me",category:"Beauty",platform:"TikTok",growth:42,status:"Em alta",score:78,description:"O formato de preparação segue forte para beleza, lifestyle e produtos."}
];
let session=null,profile=null;
const $=s=>document.querySelector(s);
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
function logo(){return `<a class="brand" href="#" onclick="home()"><span class="mark">V</span>Viraliza</a>`}
function home(){document.title="Viraliza — Antecipe o próximo hype.";$("#app").innerHTML=`<header class="top">${logo()}<nav><a href="#trends">Tendências</a><a href="#como">Como funciona</a><a href="#sobre">Sobre</a></nav><button class="btn dark" onclick="authModal('login')">Entrar</button></header><main>
<section class="hero"><div><span class="eyebrow">PLATAFORMA DE TENDÊNCIAS</span><h1>Antecipe o<br><em>próximo hype.</em></h1><p>Descubra o que está ganhando força, transforme tendências em ideias e acompanhe o desempenho do seu conteúdo.</p><div class="actions"><button class="btn dark" onclick="openPlatform()">Explorar tendências →</button><button class="btn light" onclick="authModal('signup')">Criar minha conta</button></div><small>● Tendências organizadas para inspirar seu próximo conteúdo</small></div>
<div class="radar"><div class="radarhead">Trend Radar <span>● ATUALIZADO</span></div><div class="circle"><div>TREND<br><b>RADAR</b></div></div><div class="bubble b1"><b>+87%</b>áudio viral</div><div class="bubble b2"><b>+64%</b>moda</div><div class="bubble b3"><b>+42%</b>beauty</div></div></section>
<section class="section" id="trends"><div class="sectionhead"><div><span class="eyebrow">O QUE ESTÁ ACONTECENDO</span><h2>Trends em ascensão</h2></div></div><div class="trends">${demoTrends.map(t=>trendCard(t)).join("")}</div></section>
<section class="section" id="como"><div class="sectionhead"><div><span class="eyebrow">SEM COMPLICAÇÃO</span><h2>Da tendência à ideia.</h2></div></div><div class="steps"><article><span>01</span><h3>Descubra</h3><p>Encontre tendências antes que fiquem saturadas.</p></article><article><span>02</span><h3>Entenda</h3><p>Veja crescimento, plataforma e contexto.</p></article><article><span>03</span><h3>Crie</h3><p>Transforme a trend em uma ideia para sua marca.</p></article><article><span>04</span><h3>Acompanhe</h3><p>Publique e acompanhe o desempenho.</p></article></div></section>
<section class="section" id="sobre"><div class="card"><span class="eyebrow">O DIFERENCIAL</span><h2>Não basta saber o que viraliza.</h2><p class="muted">A Viraliza conecta descoberta, criação e análise em um só lugar.</p></div></section></main><footer>Viraliza © 2026 <span>Antecipe o próximo hype.</span></footer>`}
function trendCard(t){return `<article class="trend" onclick='trendDetail(${JSON.stringify(t)})'><span class="tag">${t.status.toUpperCase()}</span><h3>${t.name}</h3><span class="meta">${t.platform} · ${t.category}</span><p>${t.description}</p><strong>↗ +${t.growth}%</strong></article>`}
async function openPlatform(){if(!configured){authModal("setup");return} const {data}=await sb.auth.getSession();session=data.session;if(!session){authModal("login");return} await loadProfile();dashboard()}
function authModal(mode){let content=mode==="setup"?`<span class="eyebrow">CONFIGURAÇÃO</span><h2>Quase lá.</h2><p class="muted">A V3 já está preparada para Supabase. Falta apenas você colocar a URL e a chave pública do seu projeto no arquivo <b>config.js</b>.</p><button class="btn dark" style="width:100%" onclick="closeModal()">Entendi</button>`:mode==="login"?`<span class="eyebrow">VIRALIZA</span><h2>Entrar</h2><label>E-mail</label><input id="email" class="input" type="email" placeholder="voce@email.com"><label>Senha</label><input id="pass" class="input" type="password" placeholder="••••••••"><button class="btn dark full" onclick="login()">Entrar →</button><p class="muted center">Ainda não tem conta? <button class="link" onclick="closeModal();authModal('signup')">Criar conta</button></p>`:`<span class="eyebrow">COMECE AGORA</span><h2>Crie sua conta.</h2><label>Nome</label><input id="name" class="input" placeholder="Seu nome ou marca"><label>Tipo de perfil</label><select id="type" class="input"><option>Marca</option><option>Criador</option><option>Influenciador</option></select><label>E-mail</label><input id="email" class="input" type="email" placeholder="voce@email.com"><label>Senha</label><input id="pass" class="input" type="password" placeholder="Mínimo de 6 caracteres"><button class="btn dark full" onclick="signup()">Criar conta →</button><p class="muted center">Já tem conta? <button class="link" onclick="closeModal();authModal('login')">Entrar</button></p>`;
modal(content)}
async function signup(){if(!sb)return;let name=$("#name").value.trim(),email=$("#email").value.trim(),password=$("#pass").value,type=$("#type").value;if(!name||!email||password.length<6)return toast("Preencha nome, e-mail e senha (6+ caracteres).");let {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:name,account_type:type}}});if(error)return toast(error.message);toast("Conta criada! Verifique seu e-mail se necessário.");closeModal();if(data.session){session=data.session;await loadProfile();dashboard()}}
async function login(){let {data,error}=await sb.auth.signInWithPassword({email:$("#email").value.trim(),password:$("#pass").value});if(error)return toast("E-mail ou senha inválidos.");session=data.session;await loadProfile();closeModal();dashboard()}
async function loadProfile(){if(!session)return;let {data,error}=await sb.from("profiles").select("*").eq("id",session.user.id).single();if(error){console.error(error);return}profile=data}
function closeModal(){$(".modalbg")?.remove()}
function modal(c){let m=document.createElement("div");m.className="modalbg";m.innerHTML=`<div class="modal"><button class="close" onclick="closeModal()">×</button>${c}</div>`;document.body.appendChild(m)}
function trendDetail(t){modal(`<span class="tag">${t.status.toUpperCase()}</span><h2>${t.name}</h2><span class="meta">${t.platform} · ${t.category}</span><p class="muted">${t.description}</p><div class="score"><span>Trend Score</span><b>${t.score}/100</b></div><div class="bar"><i style="width:${t.score}%"></i></div><p><b>Como usar:</b><br>Conecte a tendência ao seu segmento e mantenha a linguagem nativa da plataforma.</p><button class="btn dark full" onclick="closeModal();createPost('${t.id}')">Transformar em conteúdo →</button>`)}
async function getTrends(){if(!sb)return demoTrends;let {data,error}=await sb.from("trends").select("*").eq("active",true).order("score",{ascending:false});if(error){console.error(error);return demoTrends}return data||[]}
async function dashboard(){let trends=await getTrends();renderShell(false);$("#content").innerHTML=`<div class="welcome"><div><span class="eyebrow">SEU RADAR</span><h2>O que está em alta?</h2><span class="muted">Encontre oportunidades antes de todo mundo.</span></div><button class="btn dark" onclick="createPost()">+ Criar conteúdo</button></div><div class="stats"><div class="stat"><small>TRENDS</small><strong>${trends.length}</strong><span>ativas</span></div><div class="stat"><small>MEUS POSTS</small><strong id="myposts">—</strong><span>publicados</span></div><div class="stat"><small>ENGAJAMENTO</small><strong>8,7%</strong><span>médio</span></div><div class="stat"><small>OPORTUNIDADES</small><strong>${trends.filter(t=>t.status==="Emergente").length}</strong><span>emergentes</span></div></div><div class="filters">${["Todas","TikTok","Instagram","Música","Moda","Beauty"].map((x,i)=>`<button class="filter ${i===0?"active":""}" onclick="filterDash('${x}',this)">${x}</button>`).join("")}</div><div class="grid" id="dashtrends">${trends.map(dashCard).join("")}</div>`;if(sb){let {count}=await sb.from("posts").select("*",{count:"exact",head:true}).eq("user_id",session.user.id);$("#myposts").textContent=count??0}}
function dashCard(t){return `<article class="card" onclick='trendDetail(${JSON.stringify(t)})'><span class="tag">${t.status.toUpperCase()}</span><h3>${t.name}</h3><span class="meta">${t.platform} · ${t.category}</span><p>${t.description}</p><div class="score"><span>Trend Score</span><b>${t.score}/100</b></div><div class="bar"><i style="width:${t.score}%"></i></div></article>`}
async function filterDash(x,btn){document.querySelectorAll(".filter").forEach(b=>b.classList.remove("active"));btn.classList.add("active");let ts=await getTrends();$("#dashtrends").innerHTML=ts.filter(t=>x==="Todas"||t.platform===x||t.category===x).map(dashCard).join("")}
function renderShell(admin){document.getElementById("app").innerHTML=`<div class="app ${admin?"admin-theme":""}"><header class="appnav">${logo()}<div><button class="btn light" onclick="${admin?"dashboard()":"admin()"}">${admin?"← Plataforma":"Painel ADM"}</button><button class="btn dark" onclick="logout()">Sair</button></div></header><div class="layout"><aside class="side"><button class="sidelink active" onclick="${admin?"adminHome()":"dashboard()"}">▦ Visão geral</button>${admin?`<button class="sidelink" onclick="adminTrends()">◈ Gerenciar trends</button><button class="sidelink" onclick="adminUsers()">◎ Usuários</button><button class="sidelink" onclick="adminPosts()">▤ Moderação</button>`:`<button class="sidelink" onclick="radar()">◈ Trend Radar</button><button class="sidelink" onclick="createPost()">✦ Criar conteúdo</button><button class="sidelink" onclick="feed()">♡ Feed</button><button class="sidelink" onclick="profilePage()">○ Meu perfil</button><button class="sidelink" onclick="analytics()">↗ Métricas</button>`}</aside><section class="content" id="content"></section></div></div>`}
async function radar(){dashboard();setTimeout(async()=>{let ts=await getTrends();$("#content").innerHTML=`<div class="welcome"><div><span class="eyebrow">TREND RADAR</span><h2>Encontre antes de saturar.</h2></div></div><div class="grid">${ts.map(dashCard).join("")}</div>`},0)}
async function createPost(trendId=null){let ts=await getTrends();let selected=ts.find(t=>String(t.id)===String(trendId))||ts[0];modal(`<span class="eyebrow">CRIADOR</span><h2>Transforme uma trend em conteúdo.</h2><label>Tendência</label><select id="ptrend" class="input">${ts.map(t=>`<option value="${t.id}" ${selected&&t.id===selected.id?"selected":""}>${t.name}</option>`).join("")}</select><div class="row"><div><label>Formato</label><select id="format" class="input"><option>Vídeo curto</option><option>Post</option><option>Story</option><option>Carrossel</option></select></div><div><label>CTA</label><select id="cta" class="input"><option>Saiba mais</option><option>Comente</option><option>Salve este post</option><option>Confira agora</option></select></div></div><label>Imagem ou vídeo</label><input id="file" class="input" type="file" accept="image/*,video/*"><label>Legenda</label><textarea id="caption" class="textarea" placeholder="Escreva sua legenda..."></textarea><label>Hashtags</label><input id="hashtags" class="input" placeholder="#viraliza #trend #conteudo"><button class="btn dark full" onclick="publishPost()">Publicar na Viraliza →</button>`)}
async function publishPost(){if(!sb)return toast("Configure o Supabase primeiro.");let trend=await sb.from("trends").select("id,name").eq("id",$("#ptrend").value).single();if(trend.error)return toast("Trend inválida.");let file=$("#file").files[0],media_url=null;if(file){let ext=file.name.split(".").pop().toLowerCase(),path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;let up=await sb.storage.from("post-media").upload(path,file,{upsert:false});if(up.error)return toast("Falha no upload: "+up.error.message);let pub=sb.storage.from("post-media").getPublicUrl(path);media_url=pub.data.publicUrl}let caption=$("#caption").value.trim()||`Uma ideia usando ${trend.data.name}. ${$("#cta").value}!`;let {error}=await sb.from("posts").insert({user_id:session.user.id,trend_id:trend.data.id,format:$("#format").value,caption:caption+" "+$("#hashtags").value,media_url});if(error)return toast("Não foi possível publicar: "+error.message);closeModal();toast("Conteúdo publicado!");feed()}
async function feed(){renderShell(false);let {data,error}=await sb.from("posts").select("id,caption,media_url,format,created_at,likes_count,comments_count,profiles(full_name,account_type),trends(name)").order("created_at",{ascending:false});if(error)return $("#content").innerHTML=`<div class="card"><p>${error.message}</p></div>`;$("#content").innerHTML=`<div class="welcome"><div><span class="eyebrow">COMUNIDADE</span><h2>Feed da Viraliza.</h2><span class="muted">Conteúdos reais da plataforma.</span></div><button class="btn dark" onclick="createPost()">+ Criar conteúdo</button></div><div class="feed">${(data||[]).map(post=>`<article class="post">${post.media_url?`<img class="postimg real" src="${post.media_url}" alt="Conteúdo">`:`<div class="postimg">SEM MÍDIA</div>`}<div class="postbody"><div class="posthead"><b>${post.profiles?.full_name||"Usuário"}</b><span class="meta">${post.trends?.name||"Trend"}</span></div><p>${escapeHtml(post.caption||"")}</p><div class="postactions"><button class="filter" onclick="likePost('${post.id}',this)">♡ ${post.likes_count||0}</button><button class="filter" onclick="commentPost('${post.id}')">◌ ${post.comments_count||0}</button></div></div></article>`).join("")}</div>`}
async function likePost(id,btn){let {error}=await sb.rpc("toggle_like",{p_post_id:id});if(error)return toast(error.message);let r=await sb.from("posts").select("likes_count").eq("id",id).single();if(!r.error){btn.textContent="♥ "+r.data.likes_count}}
async function commentPost(id){let text=prompt("Seu comentário:");if(!text?.trim())return;let {error}=await sb.from("comments").insert({post_id:id,user_id:session.user.id,body:text.trim()});if(error)return toast(error.message);toast("Comentário adicionado!");feed()}
async function profilePage(){renderShell(false);let {data:posts}=await sb.from("posts").select("id,caption,media_url,likes_count,comments_count,trends(name)").eq("user_id",session.user.id).order("created_at",{ascending:false});$("#content").innerHTML=`<div class="welcome"><div><span class="eyebrow">MEU PERFIL</span><h2>${escapeHtml(profile?.full_name||"Meu perfil")}</h2><span class="muted">${profile?.account_type||"Criador"}</span></div><button class="btn light" onclick="editProfile()">Editar perfil</button></div><div class="stats"><div class="stat"><small>POSTS</small><strong>${posts?.length||0}</strong></div><div class="stat"><small>CURTIDAS</small><strong>${(posts||[]).reduce((a,p)=>a+(p.likes_count||0),0)}</strong></div><div class="stat"><small>COMENTÁRIOS</small><strong>${(posts||[]).reduce((a,p)=>a+(p.comments_count||0),0)}</strong></div><div class="stat"><small>TIPO</small><strong>${profile?.account_type||"—"}</strong></div></div><div class="feed">${(posts||[]).map(p=>`<article class="post">${p.media_url?`<img class="postimg real" src="${p.media_url}">`:`<div class="postimg">SEM MÍDIA</div>`}<div class="postbody"><span class="meta">${p.trends?.name||""}</span><p>${escapeHtml(p.caption||"")}</p><div class="postactions">♡ ${p.likes_count||0}　◌ ${p.comments_count||0}</div></div></article>`).join("")}</div>`}
function editProfile(){modal(`<h2>Editar perfil</h2><label>Nome</label><input id="pname" class="input" value="${escapeAttr(profile?.full_name||"")}"><label>Tipo</label><select id="ptype" class="input"><option>Marca</option><option>Criador</option><option>Influenciador</option></select><button class="btn dark full" onclick="saveProfile()">Salvar</button>`);setTimeout(()=>$("#ptype").value=profile?.account_type||"Criador",0)}
async function saveProfile(){let {error}=await sb.from("profiles").update({full_name:$("#pname").value.trim(),account_type:$("#ptype").value}).eq("id",session.user.id);if(error)return toast(error.message);await loadProfile();closeModal();profilePage();toast("Perfil atualizado!")}
async function analytics(){renderShell(false);let {data}=await sb.from("posts").select("likes_count,comments_count,trends(name)").eq("user_id",session.user.id);let total=(data||[]).reduce((a,p)=>a+(p.likes_count||0)+(p.comments_count||0),0);$("#content").innerHTML=`<div class="welcome"><div><span class="eyebrow">INSIGHTS</span><h2>Seus resultados.</h2><span class="muted">Acompanhe o desempenho dos seus conteúdos.</span></div></div><div class="stats"><div class="stat"><small>POSTS</small><strong>${data?.length||0}</strong></div><div class="stat"><small>INTERAÇÕES</small><strong>${total}</strong></div><div class="stat"><small>ENGAJAMENTO</small><strong>8,7%</strong></div><div class="stat"><small>STATUS</small><strong>Ativo</strong></div></div><div class="card"><h3>Visão geral</h3><p class="muted">Na próxima evolução, vamos adicionar gráficos históricos e métricas de alcance vindas das plataformas sociais.</p></div>`}
async function admin(){if(!profile?.is_admin)return toast("Acesso de administrador negado.");renderShell(true);adminHome()}
async function adminHome(){document.getElementById("content").innerHTML=`<div class="welcome"><div><span class="eyebrow">PAINEL ADMINISTRATIVO</span><h2>Controle da Viraliza.</h2><span class="muted">Dados reais do banco.</span></div><button class="btn dark" onclick="newTrend()">+ Nova trend</button></div><div class="stats"><div class="stat"><small>USUÁRIOS</small><strong id="au">—</strong></div><div class="stat"><small>TRENDS</small><strong id="at">—</strong></div><div class="stat"><small>POSTS</small><strong id="ap">—</strong></div><div class="stat"><small>STATUS</small><strong>Online</strong></div></div><div class="card"><h3>Últimas tendências</h3><div id="topadmin"></div></div>`;let [{count:au},{count:at},{count:ap},tr]=await Promise.all([sb.from("profiles").select("*",{count:"exact",head:true}),sb.from("trends").select("*",{count:"exact",head:true}),sb.from("posts").select("*",{count:"exact",head:true}),sb.from("trends").select("*").order("score",{ascending:false}).limit(5)]);$("#au").textContent=au??0;$("#at").textContent=at??0;$("#ap").textContent=ap??0;$("#topadmin").innerHTML=(tr.data||[]).map(t=>`<div class="adminrow"><b>${t.name}</b><span>${t.platform} · ${t.score}/100</span></div>`).join("")}
function newTrend(){modal(`<span class="eyebrow">ADMIN</span><h2>Nova tendência</h2><label>Nome</label><input id="tn" class="input"><div class="row"><div><label>Categoria</label><input id="tc" class="input"></div><div><label>Plataforma</label><select id="tp" class="input"><option>TikTok</option><option>Instagram</option><option>YouTube</option></select></div></div><div class="row"><div><label>Crescimento %</label><input id="tg" class="input" type="number" value="50"></div><div><label>Score</label><input id="ts" class="input" type="number" value="70"></div></div><label>Status</label><select id="tst" class="input"><option>Emergente</option><option>Em alta</option><option>Viral</option><option>Saturada</option></select><label>Descrição</label><textarea id="td" class="textarea"></textarea><button class="btn dark full" onclick="saveTrend()">Cadastrar</button>`)}
async function saveTrend(){let {error}=await sb.from("trends").insert({name:$("#tn").value.trim()||"Nova trend",category:$("#tc").value.trim()||"Geral",platform:$("#tp").value,growth:+$("#tg").value||50,score:+$("#ts").value||70,status:$("#tst").value,description:$("#td").value.trim()||"Trend cadastrada pelo administrador.",active:true});if(error)return toast(error.message);closeModal();toast("Trend cadastrada!");adminTrends()}
async function adminTrends(){renderShell(true);let {data,error}=await sb.from("trends").select("*").order("score",{ascending:false});if(error)return toast(error.message);$("#content").innerHTML=`<div class="welcome"><div><span class="eyebrow">ADMIN · TRENDS</span><h2>Gerenciar tendências.</h2></div><button class="btn dark" onclick="newTrend()">+ Nova trend</button></div><table class="table"><thead><tr><th>TREND</th><th>PLATAFORMA</th><th>CRESCIMENTO</th><th>SCORE</th><th>AÇÃO</th></tr></thead><tbody>${(data||[]).map(t=>`<tr><td><b>${t.name}</b><br><span class="meta">${t.category}</span></td><td>${t.platform}</td><td>+${t.growth}%</td><td>${t.score}/100</td><td><button class="filter danger" onclick="deleteTrend('${t.id}')">Excluir</button></td></tr>`).join("")}</tbody></table>`}
async function deleteTrend(id){if(!confirm("Excluir esta trend?"))return;let {error}=await sb.from("trends").delete().eq("id",id);if(error)return toast(error.message);toast("Trend excluída.");adminTrends()}
async function adminUsers(){renderShell(true);let {data,error}=await sb.from("profiles").select("*").order("created_at",{ascending:false});if(error)return toast(error.message);$("#content").innerHTML=`<div class="welcome"><div><span class="eyebrow">ADMIN · USUÁRIOS</span><h2>Usuários cadastrados.</h2></div></div><table class="table"><thead><tr><th>NOME</th><th>TIPO</th><th>STATUS</th><th>CADASTRO</th></tr></thead><tbody>${(data||[]).map(u=>`<tr><td><b>${escapeHtml(u.full_name||"Sem nome")}</b></td><td>${u.account_type||"—"}</td><td><span class="pill">${u.is_admin?"ADMIN":"USUÁRIO"}</span></td><td>${new Date(u.created_at).toLocaleDateString("pt-BR")}</td></tr>`).join("")}</tbody></table>`}
async function adminPosts(){renderShell(true);let {data,error}=await sb.from("posts").select("id,caption,media_url,created_at,profiles(full_name),trends(name)").order("created_at",{ascending:false});if(error)return toast(error.message);$("#content").innerHTML=`<div class="welcome"><div><span class="eyebrow">ADMIN · MODERAÇÃO</span><h2>Conteúdos publicados.</h2></div></div><div class="feed">${(data||[]).map(p=>`<article class="post">${p.media_url?`<img class="postimg real" src="${p.media_url}">`:`<div class="postimg">SEM MÍDIA</div>`}<div class="postbody"><div class="posthead"><b>${escapeHtml(p.profiles?.full_name||"Usuário")}</b><span class="meta">${p.trends?.name||""}</span></div><p>${escapeHtml(p.caption||"")}</p><button class="filter danger" onclick="removePost('${p.id}')">Remover</button></div></article>`).join("")}</div>`}
async function removePost(id){if(!confirm("Remover conteúdo?"))return;let {error}=await sb.from("posts").delete().eq("id",id);if(error)return toast(error.message);toast("Conteúdo removido.");adminPosts()}
async function logout(){if(sb)await sb.auth.signOut();session=null;profile=null;home()}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function escapeAttr(s){return escapeHtml(s)}
if(configured&&sb)sb.auth.onAuthStateChange((_e,s)=>{session=s});
home();
